### ISSUE TITLE
Update glossaries in appropriate REDCap instruments

### ISSUE THREAD

**Issue by rolandkrause** [rolandkrause/epi25#81]
Most important for GGE due to the changes.

**Comment by sleech** [comment]
[Epi25 EE Dictionary v1.0.1 May2020.docx](https://github.com/rolandkrause/epi25/files/4631899/Epi25.EE.Dictionary.v1.0.1.May2020.docx)
[Epi25 Focal Dictionary v1.0.1 May2020.docx](https://github.com/rolandkrause/epi25/files/4631900/Epi25.Focal.Dictionary.v1.0.1.May2020.docx)
[Epi25 GGE:mixed dictionary v1.2.0 may 2020.docx](https://github.com/rolandkrause/epi25/files/4631905/Epi25.GGE.mixed.dictionary.v1.2.0.may.2020.docx)

Hi Roland, first-pass updates to the glossaries are attached.

**Comment by sleech** [comment]
[Epi25 GGE:mixed dictionary v1.2.0 may 2020.docx](https://github.com/rolandkrause/epi25/files/4648239/Epi25.GGE.mixed.dictionary.v1.2.0.may.2020.docx)
Updated version of GGE/mixed glossary with links to eligibility criteria and edits from Sam.

**Comment by rolandkrause** [comment]
- [x] Updated the Glossaries in Luxembourg and UCSF
- [x] GGE and focal (both to versions 1.2.0) 
- [x] Placed current glossaries in Dropbox https://www.dropbox.com/sh/xorofzh7upcaqnc/AAC8VRi1daQR36Y730Sdg9R7a?dl=0
